nelmio_api_doc:
    documentation:
        info:
            title: Blog API
            description: This is an API for a Blog
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc(?:\.json)?$) # Accepts routes under /api except /api/doc

